name: Публикация сайта на GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Получить файлы сайта
        uses: actions/checkout@v7

      - name: Настроить GitHub Pages
        uses: actions/configure-pages@v6

      - name: Подготовить файлы сайта
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."

      - name: Опубликовать сайт
        id: deployment
        uses: actions/deploy-pages@v5
